<template>
    <div class="container" style="margin-top:70px;text-align:left;color:#000">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <p class="fs-4">1. Introduction</p>
                <p>This User Agreement, the Mobile Application Terms of Use, and all policies and additional terms posted on and in our sites, applications, tools and services (collectively "Services") set out the terms on which USDS offers you access to and use of our Services. You can find an overview of our policies here. The Mobile Application Terms of Use, all policies and additional terms posted on and in our Services are incorporated into this User Agreement. You agree to comply with all terms of this User Agreement when accessing or using our Services.
                    The entity you are contracting with is: USDS Inc., 2025 Hamilton Ave., San Jose, CA 95125, if you reside in the United States; USDS (UK) Limited, 1 More London Place, London, SE1 2AF, United Kingdom, if you reside in the United Kingdom; USDS GmbH, Albert-Einstein-Ring 2-6, 14532 Kleinmachnow, Germany, if you reside outside the United Kingdom but within the European Union; USDS Canada Limited, 240 Richmond Street West, 2nd Floor Suite 02-100, Toronto, Ontario, M5V 1V6, Canada, if you reside in Canada; USDS Singapore Services Pte Ltd., 10 Collyer Quay, #10-01 Ocean Financial Centre, Singapore 049315, if you reside in India; and USDS Marketplaces GmbH, Helvetiastrasse 15/17, 3005, Bern, Switzerland, if you reside in any other country. In this User Agreement, these entities are individually and collectively referred to as "USDS," "we," or "us."
                    Please be advised that this User Agreement contains provisions that govern how claims you and we have against each other are resolved (see "Disclaimer of Warranties; Limitation of Liability" and "Legal Disputes" provisions below). It also contains an Agreement to Arbitrate which will, with limited exception, require you to submit claims you have against us or our agents to binding and final arbitration, unless you opt out of the Agreement to Arbitrate (see Legal Disputes, Section B ("Agreement to Arbitrate")). If you do not opt out: (1) you will only be permitted to pursue claims against us or our agents on an individual basis, not as a plaintiff or class member in any class or representative action or proceeding and (2) you will only be permitted to seek relief (including monetary, injunctive, and declaratory relief) on an individual basis.
                </p>
                <p class="fs-4">2. About</p>
                <p>USDS is a marketplace that allows users to offer, sell and buy just about anything in a variety of pricing formats and locations. The actual contract for sale is directly between the seller and buyer. USDS is not a party to the transaction, and it is not a seller or a traditional auctioneer.
                    Any guidance we provide as part of our Services, such as pricing, shipping, listing, and sourcing is solely informational and you may decide to follow it or not. Also, while we may help facilitate the resolution of disputes through various programs, USDS has no control over and does not guarantee: the existence, quality, safety or legality of items advertised; the truth or accuracy of users' content or listings; the ability of sellers to sell items; the ability of buyers to pay for items; or that a buyer or seller will actually complete a transaction or return an item.
                </p>
                <p class="fs-4">3. Using</p>
                <p>In connection with using or accessing our Services you agree to comply with this User Agreement, our policies, our terms, and all applicable laws, rules, and regulations, and you will not:
                    post, list or upload content or items in inappropriate categories or areas on our sites;
                    breach or circumvent any laws, regulations, third-party rights or our systems, Services, policies, or determinations of your account status;
                    use our Services if you are not able to form legally binding contracts (for example, if you are under 18 years old), or are temporarily or indefinitely suspended from using our Services, or are a person with whom transactions are prohibited under economic or trade sanctions;
                    fail to pay for items purchased by you, unless you have a valid reason as set out in an USDS policy, for example, the seller has materially changed the item's description after you bid (see our Unpaid item policy);
                    fail to deliver items sold by you, unless you have a valid reason as set out in an USDS policy;
                    manipulate the price of any item or interfere with any other user's listings;
                    post false, inaccurate, misleading, deceptive, defamatory, or libelous content;
                    take any action that may undermine the feedback or ratings systems (our Feedback policies);
                    transfer your USDS account (including feedback) and user ID to another party without our consent;
                    distribute or post spam, unsolicited or bulk electronic communications, chain letters, or pyramid schemes;
                    distribute viruses or any other technologies that may harm USDS or the interests or property of users;
                    use any robot, spider, scraper, data mining tools, data gathering and extraction tools, or other automated means to access our Services for any purpose, except with the prior express permission of USDS;
                    interfere with the functioning of our Services, such as by imposing an unreasonable or disproportionately large load on our infrastructure;
                    export or re-export any USDS application or tool, except in compliance with the export control laws, and rules and policies of any relevant jurisdictions;
                    infringe the copyright, trademark, patent, publicity, moral, database, and/or other intellectual property rights (collectively, "Intellectual Property Rights") that belong to or are licensed to USDS. Some, but not all, actions that may constitute infringement are reproducing, performing, displaying, distributing, copying, reverse engineering, decompiling, disassembling, or preparing derivative works from content that belongs to USDS or someone else;
                    infringe any Intellectual Property Rights that belong to third parties affected by your use of our Services or post content that does not belong to you;
                    commercialize any USDS application or any information or software associated with such application, except with the prior express permission of USDS;
                    harvest or otherwise collect information about users without their consent; or
                    circumvent any technical measures used to provide our Services.
                    Sellers must meet USDS's minimum performance standards. Failure to meet these standards may result in USDS charging you additional fees, and/or limiting, restricting, suspending, or downgrading your seller account.

                    If we believe you are abusing USDS and/or our Services in any way, we may, in our sole discretion and without limiting other remedies, limit, suspend, or terminate your user account(s) and access to our Services, delay or remove hosted content, remove any special status associated with your account(s), remove, not display, and/or demote listings, reduce or eliminate any discounts, and take technical and/or legal steps to prevent you from using our Services.

                    If we believe you are violating our policies prohibiting Offers to buy or sell outside of USDS, you may be subject to a range of actions, including limits on your buying and selling privileges, restrictions on listings and account features, suspension of your account, application of fees, and recovery of expenses for policy monitoring and enforcement. If you are a seller and you offer or reference your contact information or ask a buyer for their contact information in the context of buying or selling outside of USDS, you may be liable to pay a final value fee applicable to that item, even if the item does not sell.

                    We may cancel unconfirmed accounts or accounts that have been inactive for a substantial period of time. Additionally, we reserve the right to refuse, modify, or terminate all or part of our Services to anyone for any reason at our discretion.
                </p>
                <p class="fs-4">4. Policy Enforcement</p>
                <p>When a buyer or seller issue arises, we may consider the user's performance history and the specific circumstances in applying our policies. We may choose to be more lenient with policy enforcement in an effort to do the right thing for both buyers and sellers. The foregoing does not limit or impair our right to refuse, modify, or terminate all or part of our Services to anyone, or to terminate this agreement with anyone, for any reason at our discretion.
                </p>
                <p class="fs-4">5. Fees and Taxes</p>
                <p>The fees we charge for using our Services are listed on our Selling fees pages. We may change our selling fees from time to time by posting the changes on the USDS site fourteen (14) days in advance, but with no advance notice required for temporary promotions or any changes that result in the reduction of fees.
                    If you are a seller, you are liable for transaction fees arising out of all sales made using some or all of our Services, even if sales terms are finalized or payment is made outside of USDS. In particular, if you offer or reference your contact information or ask a buyer for their contact information in the context of buying or selling outside of USDS, you may be liable to pay a final value fee applicable to that item, even if the item doesn't sell, given your usage of our Services for the introduction to a buyer.
                    You must have a payment method on file when selling using our Services and pay all fees and applicable taxes associated with your use of our Services by the payment due date. If your payment method fails or your account is past due, USDS payments entities may collect amounts owed in the manner described in the Payment Terms of Use. In addition, you will be subject to late fees. If you receive your sales proceeds to your PayPal account, and your account is over 60 days past due, we may request that PayPal deduct the amount owed from your PayPal account balance. USDS, or the collection agencies we retain, may also report information about your account to credit bureaus, and as a result, late payments, missed payments, or other defaults on your account may be reflected in your credit report. If you wish to dispute the information USDS reported to a credit bureau (i.e., Experian, Equifax or TransUnion) please contact us at USDS Inc., C/O Global Collections, 7700 West Parmer Lane, Building D, Austin, TX 78729. If you wish to dispute the information a collection agency reported to a credit bureau regarding your USDS account, you must contact the collection agency directly.
                    In any jurisdiction where USDS has an obligation to collect sales taxes on sales you make using our Services, we may collect such sales taxes from you via the payment method on file under the terms of the Billing Agreement or via any other means available to us.
                    Selling fees don't purchase exclusive rights to item exposure on our Services. We may display third-party advertisements (including links and references thereto) or other content in any part of our Services, in our sole discretion and without consent from, or payment, fee reduction, or other credit to, sellers.
                </p>
                <p class="fs-4">Listing Conditions</p>
                <p>You assume full responsibility for the item offered and the accuracy and content of the listing,
                    Your listing may not be immediately searchable by keyword or category for several hours (or up to 24 hours in some circumstances). USDS can't guarantee exact listing duration,
                    Your fixed-price listings may renew automatically every calendar month, based on the listing terms at the time, until all quantities sell or the listing is ended by you or USDS, in its sole discretion,
                    The content you provide complies with all of our listing policies, including the Images, videos and text policy,
                    Content that violates any of USDS's policies may be modified, obfuscated or deleted at USDS's sole discretion,
                    We may revise product data associated with listings to supplement, remove, or correct information,
                    We strive to create a marketplace where buyers find what they are looking for. Therefore, the appearance or placement of listings in search and browse results will depend on a variety of factors, including, but not limited to:
                    buyer's location, search query, browsing site, and history;
                    item's location, listing format, price and shipping cost, terms of service, end time, history, and relevance to the user query;
                    seller's history, including listing practices, Detailed Seller Ratings, USDS policy compliance, feedback, and defect rate; and
                    number of listings matching the buyer's query,
                    To drive a positive user experience, a listing may not appear in some search and browse results regardless of the sort order chosen by the buyer,
                    Some advanced listing upgrades will only be visible on some of our Services,
                    USDS's Duplicate listings policy may also affect whether your listing appears in search results,
                    Metatags and URL links that are included in a listing may be removed or altered so as to not affect third-party search engine results,
                    We may provide you with optional recommendations to consider when creating your listings. Such recommendations may be based on the aggregated sales and performance history of similar sold and current listings; results may vary for individual listings. To drive the recommendations experience, you agree that we may display the sales and performance history of your individual listings to other sellers,
                    For items listed in certain categories, subject to certain programs, and/or offered or sold at certain price points, USDS may require the use of certain payment methods, subject to our Payments methods policy. For example, for inventory covered by authentication services, buyer and sellers may be subject to escrow and/or payment handling requirements,
                    You will not sell and will promptly remove all listings for any product recalled by a manufacturer or governmental agency if the sale of the product is prohibited by law or regulation or the product poses a health or safety hazard as specified by any governmental agency. USDS has no responsibility or liability for the safety or performance of any product that you list or sell using our Services, including any product that is subject to a recall. You are solely responsible for any non-conformity or defect in, or compliance with any public or private recall of any product you list or sell using our Services.
                </p>
                <p class="fs-4">7. Purchase Conditions</p>
                <p>When buying an item on our Services, you agree to the Rules and policies for buyers and that:
                    You are responsible for reading the full item listing before making a bid or committing to buy,
                    You enter into a legally binding contract to purchase an item when you commit to buy an item, your offer for an item is accepted, or if you have the winning bid (or your bid is otherwise accepted),
                    For motor vehicles and real estate, a bid or offer initiates a non-binding transaction representing a buyer's serious expression of interest in buying the seller's item and does not create a formal contract between the buyer and the seller,
                    We do not transfer legal ownership of items from the seller to you,
                    Utah Code Annotated § 70A-2-401(2) and Uniform Commercial Code § 2-401(2) apply to the transfer of ownership between the buyer and the seller, unless the buyer and the seller agree otherwise.
                </p>
                <p class="fs-4">8. International Buying and Selling; Translation</p>
                <p>Many of our Services are accessible internationally. We may offer certain programs, tools, and site experiences of particular interest to international sellers and buyers, such as estimated local currency conversion and international shipping calculation tools. Sellers and buyers are responsible for complying with all laws and regulations applicable to the international sale, purchase, and shipment of items.
                    If you purchase an item on an USDS site that is different from your registration site, you are subject to the User Agreement and applicable policies of that other USDS site with respect to that particular purchase, as detailed in the International selling policy.
                    For sellers, you agree that we may display your listing for sale on an USDS site other than the site where you listed your item for sale, based on your shipping settings. You may adjust these settings as detailed in the International selling policy. If you list your items with an international shipping option, the appearance of your listings on sites other than the listing site is not guaranteed. If you sell an item on an USDS site that is different from your registration site, you are subject to the User Agreement and applicable policies, including any buyer protection programs, of that other USDS site with respect to that particular sale, as detailed in the International selling policy.
                    You authorize us to use automated tools to translate your USDS content and member-to-member communications, in whole or in part, into local languages where such translation solutions are available. We may provide you with tools which will enable you to translate content at your request. The accuracy and availability of any translation are not guaranteed.
                    One of the ways that we may make USDS.com listings available to international buyers on USDS.com and on USDS's international sites is through the Global Shipping Program. For eligible items located in the United States and purchased by an international buyer through the Global Shipping Program, you (as seller) will simply ship the item to a parcel processing facility located in the United States after receiving notification of payment from the buyer. Pitney Bowes Inc., a third-party global shipping provider, will oversee the processing, customs clearance, and international shipment of the item on behalf of your international buyer. To the extent a buyer has a question about your Global Shipping Program listings, USDS may respond directly to the buyer if the question pertains to the services overseen by Pitney Bowes Inc. (for example, customs or international shipping). Sellers pay no additional fees for selling through the Global Shipping Program.
                    Pursuant to a routed export transaction under the U.S. Export Administration Regulations and Foreign Trade Regulations, the buyer, as the Foreign Principal Party in Interest, will agree to assume responsibility for the export shipment, with Pitney Bowes Inc. acting as your buyer's forwarding agent. You remain liable for the accuracy of information you provide about items, and you agree to provide timely responses to requests for additional information.
                    You consent to the disclosure of certain personally identifiable information, as well as listing and order information, by USDS to Pitney Bowes Inc., and by Pitney Bowes Inc. to its affiliates, service providers, and other third parties (such as customs and revenue authorities, as well as other government agencies), in connection with the processing, export and customs clearance, and international transportation of any item. USDS does not control the privacy policies of Pitney Bowes Inc., its affiliates, or its service providers, and you are subject to the privacy policies of those parties, as applicable.
                    Additional information about the program, including policies governing feedback, the handling of lost, damaged, and undeliverable items, returns, and the resolution of buyer protection claims for items that you sell through the program, can be found on our Global Shipping Program and Global Shipping FAQs pages.
                </p>
                <p class="fs-4">9. Content</p>
                <p>When you provide content using our Services (directly or indirectly), you grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sublicensable (through multiple tiers) right to exercise any and all Intellectual Property Rights you have in that content in connection with our provision, expansion, and promotion of our Services, in any media known now or developed in the future. To the fullest extent permitted under applicable law, you waive your right to enforce your Intellectual Property Rights in that content against USDS, our assignees, our sublicensees, and their assignees in connection with our, those assignees', and those sublicensees' use of that content in connection with our provision, expansion, and promotion of our Services.
                    You represent and warrant that, for all such content you provide, you own or otherwise control all necessary rights to do so and to meet your obligations under this User Agreement. You represent and warrant that such content is accurate. You represent and warrant that use of any such content (including derivative works) by us, our users, or others in contract with us, and in compliance with this User Agreement, does not and will not infringe any Intellectual Property Rights of any third party. USDS takes no responsibility and assumes no liability for any content provided by you or any third party.
                    We offer product data (including images, descriptions and specifications) that are provided by third parties (including USDS users). You may use that content solely in your USDS listings. USDS may modify or revoke that permission at any time in our sole discretion. The product data includes copyrighted, trademarked and other proprietary materials. You agree not to remove any copyright, proprietary, or identification markings in the product data and not to create any derivative works based on that data (other than by including the data in your listings).
                    We try to offer reliable product data, but cannot promise that the content provided through our Services will always be available, accurate, complete, and up-to-date. You agree that USDS is not responsible for examining or warranting the listings or content provided by third parties through our Services, and that you will not attempt to hold us or our data providers liable for inaccuracies
                    The name "USDS" and other USDS marks, logos, designs, and phrases that we use in connection with our Services are trademarks, service marks, or trade dress of USDS in the U.S. and other countries. They may not be used without the express written prior permission of USDS.
                </p>
            </div>
        </div>
    </div>
</template>

<script setup>
name:'UserAgreement';
</script>

<style lang="scss" scoped>

</style>